/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Email = IDL.Text;
export const AuthenticatedPrincipal = IDL.Variant({
  'internetIdentity' : IDL.Principal,
  'emailPassword' : Email,
});
export const Timestamp = IDL.Int;
export const AuthToken = IDL.Text;
export const Session = IDL.Record({
  'created' : Timestamp,
  'token' : AuthToken,
  'lastAccessed' : Timestamp,
  'expiration' : Timestamp,
});
export const LoginResult = IDL.Variant({
  'failure' : IDL.Record({ 'message' : IDL.Text }),
  'success' : IDL.Record({
    'user' : AuthenticatedPrincipal,
    'session' : IDL.Opt(Session),
    'message' : IDL.Text,
    'sessionToken' : IDL.Text,
  }),
});
export const LogoutResult = IDL.Variant({
  'failure' : IDL.Record({ 'message' : IDL.Text }),
  'success' : IDL.Record({ 'message' : IDL.Text }),
});
export const SignupResult = IDL.Variant({
  'failure' : IDL.Record({ 'message' : IDL.Text }),
  'success' : IDL.Record({
    'user' : AuthenticatedPrincipal,
    'session' : IDL.Opt(Session),
    'message' : IDL.Text,
    'sessionToken' : IDL.Text,
  }),
});
export const SessionValidationResult = IDL.Record({
  'user' : IDL.Opt(AuthenticatedPrincipal),
  'session' : IDL.Opt(Session),
  'message' : IDL.Text,
  'isValid' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([IDL.Text], [LogoutResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'signup' : IDL.Func([IDL.Text, IDL.Text], [SignupResult], []),
  'validateSession' : IDL.Func(
      [IDL.Text],
      [SessionValidationResult],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Email = IDL.Text;
  const AuthenticatedPrincipal = IDL.Variant({
    'internetIdentity' : IDL.Principal,
    'emailPassword' : Email,
  });
  const Timestamp = IDL.Int;
  const AuthToken = IDL.Text;
  const Session = IDL.Record({
    'created' : Timestamp,
    'token' : AuthToken,
    'lastAccessed' : Timestamp,
    'expiration' : Timestamp,
  });
  const LoginResult = IDL.Variant({
    'failure' : IDL.Record({ 'message' : IDL.Text }),
    'success' : IDL.Record({
      'user' : AuthenticatedPrincipal,
      'session' : IDL.Opt(Session),
      'message' : IDL.Text,
      'sessionToken' : IDL.Text,
    }),
  });
  const LogoutResult = IDL.Variant({
    'failure' : IDL.Record({ 'message' : IDL.Text }),
    'success' : IDL.Record({ 'message' : IDL.Text }),
  });
  const SignupResult = IDL.Variant({
    'failure' : IDL.Record({ 'message' : IDL.Text }),
    'success' : IDL.Record({
      'user' : AuthenticatedPrincipal,
      'session' : IDL.Opt(Session),
      'message' : IDL.Text,
      'sessionToken' : IDL.Text,
    }),
  });
  const SessionValidationResult = IDL.Record({
    'user' : IDL.Opt(AuthenticatedPrincipal),
    'session' : IDL.Opt(Session),
    'message' : IDL.Text,
    'isValid' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([IDL.Text], [LogoutResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'signup' : IDL.Func([IDL.Text, IDL.Text], [SignupResult], []),
    'validateSession' : IDL.Func(
        [IDL.Text],
        [SessionValidationResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };